FROM ghcr.io/graalvm/graalvm-ce:java17-21

MAINTAINER Adam Kovari <kovariadam@gmail.com>

#RUN gu install native-image

ADD component/yona-component.jar .
RUN gu install -L yona-component.jar

WORKDIR /sources

ENTRYPOINT ["/opt/graalvm-ce-java17-21.3.0/bin/yona"]
