FROM docker.pkg.github.com/graalvm/container/community:21.2.0-java16-amd64

MAINTAINER Adam Kovari <kovariadam@gmail.com>

#RUN gu install native-image

ADD component/yona-component.jar .
RUN gu install -L yona-component.jar

RUN alternatives --remove yona /opt/graalvm-ce-java16-21.2.0//bin/yona

WORKDIR /sources

ENTRYPOINT ["/opt/graalvm-ce-java16-21.2.0/bin/yona"]
