#!/usr/bin/env bash

VERSION="21.2.0"

MAIN_CLASS="yona.Launcher"
SCRIPT_HOME="$(cd "$(dirname "$0")" && pwd -P)"

function extractGraalVMVersion() {
    local -r releasePath="${1:?Path to release file is a required parameter}"
    grep "GRAALVM_VERSION" "$releasePath" 2> /dev/null \
        | awk 'BEGIN {FS="="} {print $2}' \
        | sed 's/"//g'
}

function versionCheck() {
    local -r message="${1:-Wrong GraalVM version.}"
    if [[ "$GRAALVM_VERSION" != "$VERSION" ]]; then
        fail "$message"
    fi
}

function fail() {
    local -r message="${1:-Unknown error}"
    local -r exitCode="${2:-1}"
    >&2 echo "$message"
    exit "$exitCode"
}

#######################################################################
# Locations of the language and launcher jars as well as the java command are
# different if I'm running from the repository or as a component in GraalVM
#######################################################################
GRAALVM_VERSION=$(extractGraalVMVersion "$SCRIPT_HOME/../release")
if [[ "$GRAALVM_VERSION" != "" ]]; then
    LANGUAGE_PATH="$SCRIPT_HOME/../languages/yona/language/language.jar"
    LAUNCHER_PATH="$SCRIPT_HOME/../languages/yona/launcher/yona-launcher.jar"
    JAVACMD="$SCRIPT_HOME/java"
    versionCheck "Installed in wrong version of GraalVM. Expected: $VERSION, found $GRAALVM_VERSION"
else
    LANGUAGE_PATH="$SCRIPT_HOME/language/target/language.jar"
    LAUNCHER_PATH="$SCRIPT_HOME/launcher/target/yona-launcher.jar"
    # Check the GraalVM version in JAVA_HOME
    if [[ "$JAVA_HOME" != "" ]]; then
        GRAALVM_VERSION=$(extractGraalVMVersion "$JAVA_HOME"/release)
        if [[ "$GRAALVM_VERSION" != "" ]]; then
            versionCheck "Wrong version of GraalVM in \$JAVA_HOME. Expected: $VERSION, found $GRAALVM_VERSION"
        fi
        JAVACMD=${JAVACMD:=$JAVA_HOME/bin/java}
        if [[ ! -f $LANGUAGE_PATH ]]; then
            fail "Could not find language on $LANGUAGE_PATH. Did you run mvn package?"
        fi
        if [[ ! -f $LAUNCHER_PATH ]]; then
            fail "Could not find launcher on $LAUNCHER_PATH. Did you run mvn package?"
        fi
    else
        fail "JAVA_HOME is not set"
        exit 1
    fi
fi

#######################################################################
# Parse arguments, prepare Java command and execute
#######################################################################
if [[ "$GRAALVM_VERSION" != "" ]]; then
    PROGRAM_ARGS=()
    JAVA_ARGS=()

    for opt in "$@"
    do
      case $opt in
        -debug)
            JAVA_ARGS+=("-Xdebug" "-Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y") ;;
        -dump)
            JAVA_ARGS+=("-Dpolyglot.engine.AllowExperimentalOptions=true" "-Dgraal.Dump=Truffle:2" "-Dpolyglot.engine.BackgroundCompilation=false" "-Dpolyglot.engine.TraceCompilation=true" "-Dpolyglot.engine.TraceCompilationDetails=true" "-Dgraal.FullUnroll=false" "-Dgraal.PartialUnroll=false" "-Dgraal.LoopPeeling=false" "-Dgraal.LoopUnswitch=false" "-Dgraal.OptScheduleOutOfLoops=false") ;;
        -disassemble)
            JAVA_ARGS+=("-Dpolyglot.engine.AllowExperimentalOptions=true" "-XX:CompileCommand=print,*OptimizedCallTarget.profiledPERoot" "-XX:CompileCommand=exclude,*OptimizedCallTarget.profiledPERoot" "-Dpolyglot.engine.BackgroundCompilation=false" "-Dpolyglot.engine.TraceCompilation=true" "-Dpolyglot.engine.TraceCompilationDetails=true") ;;
        -J*)
            opt=${opt:2}
            JAVA_ARGS+=("$opt") ;;
        *)
            PROGRAM_ARGS+=("$opt") ;;
      esac
    done
    "$JAVACMD" "${JAVA_ARGS[@]}" -Dtruffle.class.path.append="$LANGUAGE_PATH" -cp "$LAUNCHER_PATH:$JAVA_HOME/lib/graalvm/launcher-common.jar:$JAVA_HOME/lib/truffle/truffle-dsl-processor.jar" "$MAIN_CLASS" "${PROGRAM_ARGS[@]}"
else
    echo "Warning: Could not find GraalVM on $JAVA_HOME. Running on JDK without support for compilation."
    echo
    PROGRAM_ARGS=()
    JAVA_ARGS=()

    for opt in "$@"
    do
      case $opt in
        -debug)
            JAVA_ARGS+=("-Xdebug" "-Xrunjdwp:transport=dt_socket,server=y,address=8000,suspend=y") ;;
        -dump)
            echo "NOTE: Ignoring -dump, only supported on GraalVM." ;;
        -disassemble)
            echo "NOTE: Ignoring -disassemble" ;;
        -J*)
            opt=${opt:2}
            JAVA_ARGS+=("$opt") ;;
        *)
            PROGRAM_ARGS+=("$opt") ;;
      esac
    done
    if [[ ! -d $HOME/.m2 ]]; then
        echo "Could not find mvn cache at $HOME/.m2"
        exit 1
    fi
    GRAAL_SDK_PATH="$HOME/.m2/repository/org/graalvm/graal-sdk/sdk/$TRUFFLE_VERSION/graal-sdk-$TRUFFLE_VERSION.jar"
    GRAAL_LAUNCHER_PATH="$HOME/.m2/repository/org/graalvm/sdk/launcher-common/$TRUFFLE_VERSION/launcher-common-$TRUFFLE_VERSION.jar"
    TRUFFLE_API_PATH="$HOME/.m2/repository/org/graalvm/truffle/truffle-api/$TRUFFLE_VERSION/truffle-api-$TRUFFLE_VERSION.jar"
    ANTLR_PATH="$HOME/.m2/repository/org/antlr/antlr4-runtime/4.9.2/antlr4-runtime-4.9.2.jar"
    "$JAVACMD" "${JAVA_ARGS[@]}" -cp "$GRAAL_SDK_PATH":"$GRAAL_LAUNCHER_PATH":"$LAUNCHER_PATH":"$TRUFFLE_API_PATH":"$ANTLR_PATH" "$MAIN_CLASS" $PROGRAM_ARGS
fi
