#version 450

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer FlagBuf {
    int flags[];
};

layout(set = 0, binding = 1) buffer OutBuf {
    int elems[];
};

layout(push_constant) uniform Push {
    uint elem_count;
};

void main() {
    uint gid = gl_GlobalInvocationID.x;
    if (gid >= elem_count) return;
    elems[gid] = (flags[int(gid)] != 0) ? 1 : 0;
}
