#version 450
#extension GL_ARB_gpu_shader_int64 : require

layout(local_size_x = 64, local_size_y = 1, local_size_z = 1) in;

layout(set = 0, binding = 0) buffer Data {
    int64_t elems[];
};

layout(push_constant) uniform Push {
    int64_t unused;
    uint elem_count;
};

void main() {
    uint idx = gl_GlobalInvocationID.x;
    if (idx >= elem_count) return;
    int64_t v = elems[idx];
    elems[idx] = v * v;
}
