# Official Windows clang+llvm import libs often hardcode
#   .../2022/Enterprise/DIA SDK/lib/amd64/diaguids.lib
# Find a real diaguids.lib via vswhere, then rewrite LLVM imported targets.

function(yona_find_diaguids_lib out_var)
	set(_found "")
	set(_vswhere "")
	if(DEFINED ENV{ProgramFiles\(x86\)} AND EXISTS "$ENV{ProgramFiles\(x86\)}/Microsoft Visual Studio/Installer/vswhere.exe")
		set(_vswhere "$ENV{ProgramFiles\(x86\)}/Microsoft Visual Studio/Installer/vswhere.exe")
	endif()
	if(_vswhere)
		execute_process(
			COMMAND "${_vswhere}" -products * -property installationPath
			OUTPUT_VARIABLE _vs_roots
			OUTPUT_STRIP_TRAILING_WHITESPACE
			ERROR_QUIET
		)
		string(REPLACE "\n" ";" _vs_root_list "${_vs_roots}")
		foreach(_root IN LISTS _vs_root_list)
			string(STRIP "${_root}" _root)
			if(_root AND EXISTS "${_root}/DIA SDK/lib/amd64/diaguids.lib")
				set(_found "${_root}/DIA SDK/lib/amd64/diaguids.lib")
				break()
			endif()
		endforeach()
	endif()
	if(NOT _found)
		set(_pf_roots "")
		if(DEFINED ENV{ProgramFiles} AND NOT "$ENV{ProgramFiles}" STREQUAL "")
			list(APPEND _pf_roots "$ENV{ProgramFiles}/Microsoft Visual Studio")
		endif()
		if(DEFINED ENV{ProgramFiles\(x86\)} AND NOT "$ENV{ProgramFiles\(x86\)}" STREQUAL "")
			list(APPEND _pf_roots "$ENV{ProgramFiles\(x86\)}/Microsoft Visual Studio")
		endif()
		foreach(_year IN ITEMS 2022 2025 2026 18)
			foreach(_sku IN ITEMS Enterprise Professional Community BuildTools)
				foreach(_pf IN LISTS _pf_roots)
					set(_cand "${_pf}/${_year}/${_sku}/DIA SDK/lib/amd64/diaguids.lib")
					if(EXISTS "${_cand}")
						set(_found "${_cand}")
						break()
					endif()
				endforeach()
				if(_found)
					break()
				endif()
			endforeach()
			if(_found)
				break()
			endif()
		endforeach()
	endif()
	set(${out_var} "${_found}" PARENT_SCOPE)
endfunction()

function(yona_remap_llvm_dia_sdk)
	if(NOT WIN32)
		return()
	endif()
	yona_find_diaguids_lib(_yona_dia)
	if(NOT _yona_dia)
		message(STATUS "DIA SDK diaguids.lib not found — LLVM PDB link may fail")
		return()
	endif()
	message(STATUS "DIA SDK: ${_yona_dia}")

	set(_props
		INTERFACE_LINK_LIBRARIES
		IMPORTED_LINK_INTERFACE_LIBRARIES
		IMPORTED_LINK_INTERFACE_LIBRARIES_RELEASE
		IMPORTED_LINK_INTERFACE_LIBRARIES_DEBUG
		IMPORTED_LINK_INTERFACE_LIBRARIES_RELWITHDEBINFO
		IMPORTED_LINK_INTERFACE_LIBRARIES_MINSIZEREL
	)
	get_property(_imported DIRECTORY PROPERTY IMPORTED_TARGETS)
	foreach(_t IN LISTS _imported)
		if(NOT _t MATCHES "^LLVM")
			continue()
		endif()
		foreach(_prop IN LISTS _props)
			get_target_property(_libs "${_t}" ${_prop})
			if(NOT _libs)
				continue()
			endif()
			set(_new "")
			set(_changed FALSE)
			foreach(_lib IN LISTS _libs)
				if(_lib MATCHES "DIA SDK" AND NOT EXISTS "${_lib}")
					list(APPEND _new "${_yona_dia}")
					set(_changed TRUE)
				else()
					list(APPEND _new "${_lib}")
				endif()
			endforeach()
			if(_changed)
				set_property(TARGET "${_t}" PROPERTY ${_prop} "${_new}")
			endif()
		endforeach()
	endforeach()
endfunction()

yona_remap_llvm_dia_sdk()
